version: '3'

networks:
  backend:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app-container
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./src:/app/src
    working_dir: /app
    networks:
      - backend
    env_file:
      - .env